### ISSUE TITLE
unlabeled annotation properties in ecrro.owl

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#1]
There are a bunch of annotation properties without labels in the ontology, like IAO_0000117, NCIT_P207, RO_001900, BFO_0000180. Judging from their usage, they would appear to have some consistent semantics, but need human-intelligible labels to be useful.

**Comment by rduerr** [comment]
I was trying to minimize the amount of information imported; so did not include annotations.  However, I agree that labels and definitions would be handy...  That will take a couple of hours or so to fix given how many imports there are....

**Comment by rduerr** [comment]
It looks like you've done that...?  Did you get all of them?  I also noted the addition of source ontology prefixes

**Comment by smrgeoinfo** [comment]
fixed with commit 0b863d25a6775a3ee9eb50e06c781dbfb1768207

**Comment by smrgeoinfo** [comment]
I added the labels and definitions, will push now
