### ISSUE TITLE
add document as resource type.

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#10]
For new term requests, please provide the following information:

## Preferred term label
Document

## Textual definition
A resource that is a package of content intended for human consumption, typically with text and images.  The EarthCube Resource Registry scope is intended to include documents specifically related to EarthCube policy, operations, and recommendations

## Suggested parent term
ecrr:ECResource
## Attribution
orcid:0000-0001-6041-5302

**Comment by rduerr** [comment]
Actually, many of the existing ECResources are documents (e.g., specifications, use cases, etc.) so this natural.

**Comment by rduerr** [comment]
Implemented using FOAF:document as the parent.

**Comment by rduerr** [comment]
As of 10/23/2019 there is no ECResource type of document.  Will not be implemented during this contract.
