### ISSUE TITLE
Do services, interfaceAPI's, repositories and platforms need date information?

### ISSUE THREAD

**Issue by rduerr** [earthcubearchitecture-ecresourcereg/ecrro#14]
The [ResourceDescription testing 2019-05 document](https://docs.google.com/spreadsheets/d/1MJTBvUaqTBbkBJ4mY8aKiSrxOjzcOUSGgho7rWcSM3s/edit?usp=sharing) only has a dates column for service not that other three.  Which if any need dates?

**Comment by smrgeoinfo** [comment]
actually, it's not clear what the use cases are for date information on services, interfaces, repositories, platforms.  Date deployed? Services and interfaces should be associated with a specification that has a publicationDate.   I suppose if a repository stopped taking new content there would be an 'inactive' date?

Off the cuff I'd say unnecessary or optional.

**Comment by rduerr** [comment]
Implemented as optional
