### ISSUE TITLE
in redwork branch, citation and EC citation

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#15]
Why are there two citation properties
citation http://purl.obolibrary.org/obo/ECRRO_0000009
and 
EC resource citation (child of citation) http://purl.obolibrary.org/obo/ECRRO_0000062 ?

I'm using 0000009 in the test examples.

**Comment by rduerr** [comment]
Citation (ECRRO_0000009) is a generic citation of which many will not be EC resource citations (ECRRO_0000062).  It's called a poor attempt at trying to make the ontology reusable outside of EarthCube.
