### ISSUE TITLE
primary publication should be a property/role, not a class

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#17]
Seems that primaryPublication should be an object property with domain Resource and range Document, instead of a class.  Its only primary with respect to some other resource.

**Comment by smrgeoinfo** [comment]
currently have 
schema:publication max 1 (schema:CreativeWork or schema:URL)

but in the sdo documentation,  have "Values expected to be one of these types--PublicationEvent", so docs throw error in Google Structured Data Testing Tool.

**Comment by rduerr** [comment]
Actually the publication referred to in the ontology is not the sdo:publication but is IAO:0000311 (publication) so your mapping is wrong.

**Comment by smrgeoinfo** [comment]
I got tricked by the implementation in 'Resource Descriptions 2019-09' google sheet and 'FormsSpreadsheetsMapping2JSON-LD' google sheet which both pointed to sdo:publication for the property.  IAO:0000311 is "A document that has been accepted by a publisher", which seems to be somewhat different from 'primary publication', which to me connotes a particular role relative to the described resource, but it will work. I'll update the spreadsheets to align with the ontology.

**Comment by smrgeoinfo** [comment]
primaryPublication is object property we need See PR #29

**Comment by rduerr** [comment]
fixed and pushed to redwork

**Comment by rduerr** [comment]
Merged to master yesteray
