### ISSUE TITLE
change import owl file extension from owl to rdf

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#2]
I'm working on instances using TopBraid, and it no longer recognizes .owl files. It looks like all the imports are rdf/xml.  I'd like to change the file extensions in the imports directory to .rdf.  @rduerr do you see any problem?

**Comment by rduerr** [comment]
Just tested doing that in protege and no problem.  So go ahead... Let me know when done and I'll repull!

**Comment by rduerr** [comment]
Also I note that I've been adding all the resource types under 'Catalogued resource' as per dcat profile instructions, though am not yet done.  You might want to hold off on the instancing until that is done....

**Comment by rduerr** [comment]
Whoops!  I forgot that the OBO Foundry processes expect owl and obo files, though that can be tailored.  Please look that up and make the appropriate configuration changes to this repo.

**Comment by rduerr** [comment]
Worse yet, it is no longer possible to open the ontology in Protege - rolling back last commits.

**Comment by smrgeoinfo** [comment]
I moved work to a branch where I can make adjustments for topBraid; probably won't try to merge that back to master, just manually sync periodically.

**Comment by smrgeoinfo** [comment]
Ruth—there’s a pull request with a fix that you can pull into master if it looks good to you.

steve
