### ISSUE TITLE
scienceDomains/Disciplines

### ISSUE THREAD

**Issue by rduerr** [earthcubearchitecture-ecresourcereg/ecrro#22]
There are several lists of scientific domains, academic domains, etc.  However, Bepress has taken the main ones and come up with a 3-tier classification somewhat similar to GCMD's scientific keywords.  Since they work with many publishers it makes sense to me to be consistent with their scheme.  I've asked for an rdf/owl copy - we'll see what I get.  I also note that they already have tooling that possibly could be reused to select terms... (not sure).

**Comment by rduerr** [comment]
[Uploading bepress_disciplines_taxonomy_2019-01.docx…]()

**Comment by smrgeoinfo** [comment]
link to draft document doesn't work.  I'd like to start updating the test descriptions from this vocabulary.

**Comment by rduerr** [comment]
Actually a separate ontology has created and is in github at https://github.com/earthcubearchitecture-ecresourcereg/Utility-Ontologies/blob/master/ADO.rdf
