### ISSUE TITLE
need ecrro:applicationInterface property 

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#25]
EC_Software and EC_Servie need ecrro:applicationInterface property with range eccro:0000207 (ecrro Interface_API) or Text or URL . I can't find the property in the ontology
Should/can we use hydra: or some other vocab for this?

**Comment by rduerr** [comment]
Well I looked at the Hydra terminology and couldn't find anything that obviously fit here.  I can add this though you know since ecrro:Interface_API is an ARK, we could get by with Text or URL

**Comment by smrgeoinfo** [comment]
I'm fine with eccro:applicationInterface with a Text or URL property.   We can point out in scope notes that ideally the URL would be a URI for a registered EC Interface_API

**Comment by rduerr** [comment]
OK, will implement after my upcoming 2 hour (ugh...) telecon.

**Comment by smrgeoinfo** [comment]
hasInterface (http://purl.obolibrary.org/obo/ecrro.owl/ECRRO_000173) was already pulled in to redwork branch  with PR #29, that solves the problem.  I think we can close.

**Comment by rduerr** [comment]
Agreed
