### ISSUE TITLE
need eccro profileOf property

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#28]
profileOf property,  for [specification resource type](https://docs.google.com/spreadsheets/d/1W3GXxVuATqsqJVc8UGTWbLd3iXsgQNxCnnLxB77LnPc/edit#gid=966959339). Range is URI or Text.

**Comment by rduerr** [comment]
Actually ECRRO_0000166 (profile of) already exists with range ECResource or Text or URL - I can change that to be "EC Specification" or Text or URL.  Is that what is needed?  Let me know and I'll push that to master.

**Comment by smrgeoinfo** [comment]
addressed by PR #29
