### ISSUE TITLE
registration metadata

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#31]
ontology currently has a ecrro:CatalogRecord class to account for metadata about the resource registration. This follows the DCAT pattern of nesting the actual resource description inside a CatalogRecord object.  This is not how schema.org does things, and the pattern would be quite contorted (AFAICT) to implement in SDO.  Therefore, I think we need to implement a 'RegistrationRecord' object and 'registrationMetadata' property on sdo:CreativeWork in the ontology.  Something like this:

"@type":"CreativeWork", 
....
"ecrro:registrationMetadata": {
    "@type":"ecrro:RegistrationRecord",
    "dc:contributor":{
        "@type":"Person",
        "name":"Joe Metadata",
        "identifier":"orcid:...."}
    "datePublished":"2018-07-02",
    "dateModified":"2019-10-10"
}

The registration metadata lists the contributor of the metadata record, the date created, and date of the most recent update.  Prefer using contributor to avoid possible confusion with the creator of the described resource.  I'll create a branch in ecrro Github repo with the proposed addition.

This solves #19

**Comment by smrgeoinfo** [comment]
pull request #33 addresses the issue

**Comment by rduerr** [comment]
hmmm.... I merged your other request earlier today and it has left a number of unresolved reasoning errors that I am exploring.  I will consider this after those are resolved.

**Comment by rduerr** [comment]
What does AFAICT mean?

Also, information about the resource is in ECResource.  
Information about the record is in EC Catalog Record.
The link between them is that the "primary topic" of the EC Catalog Record is an ECResource.

In other words, I do not understand the first two sentences in your problem statement.  They make no sense to me.

I don't understand why you think the following doesn't work:

"@type":"CreativeWork",
....
"some Ark for the metadata record": {
"@type":"ecrro:EC Catalog Record",
"dc:contributor":{
"@type":"Person",
"name":"Joe Metadata",
"identifier":"orcid:...."}
"datePublished":"2018-07-02",
"dateModified":"2019-10-10",
"primary topic":"the Ark of the resource"
}
}

**Comment by smrgeoinfo** [comment]
Interesting Idea, and looks like it could work. Will throw an error on the schema.org structured data testing tool.  seems conceptually circular from an rdf point of view 'x is a property of x'....

**Comment by rduerr** [comment]
not really circular as the two ARK's are different as the two records are different...

**Comment by smrgeoinfo** [comment]
Currently we are not generating separate identifers (ark or otherwise) for the description of the catalog record ("@type":"ecrro:EC Catalog Record") and for the description of the resource ("@type":"sdo:CreativeWork"), so there is no way to establish an sdo:contributor triple that is about the catalogRecord instead of the Resource. That's the problem.

As I understand things, the ark's we create identify the catalog record (registryItem), and the sdo:identifier within the catalog record identifies the resource that the catalog record describes.

**Comment by rduerr** [comment]
Uhhh... when was that decision made?  We had been discussing the two records for months now, so that is how I implemented it!

**Comment by smrgeoinfo** [comment]
I don't see a problem between the ontology (conceptual model) and the implementation. There is a 1:1 relationship between the CatalogRecord (registration metadata) and the resource description bound to that registration;  The JSON-LD metadata documents we generate from the google form or test descriptions spreadsheet are the resource descriptions. From an implementation point of view, there's no reason to create separate identifiers.  The @id in the JSON LD identifies the resource description that has a 1:1 relationship with the CatalogRecord.   The pattern is implicit in DCAT v2 (there is not a separate identifier on dcat:CatalogRecord) and explicit in the ISO19115 xml implementations (gmd:fileIdentifier vs. gmd:identificationInformation/.../gmd/CI_Citation/.../gmd:identifier).  

Is there some use case that isn't addressed by this approach?

**Comment by rduerr** [comment]
See comment on #19

**Comment by smrgeoinfo** [comment]
solution:
ecrro:registrationMetadata has type EC_CatalogRecord; need to add identifier in the catalog record instances.  MInt arks: for the catalogRecord instance.  Change contributor to creator.

**Comment by smrgeoinfo** [comment]
This is now resolved by new PR #38
