### ISSUE TITLE
labeled links for values of ecrro properties

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#34]
many of the properties defined in the ECRR ontology take either text or a URI/URL.  It makes documents much more readable if the URI/URL values have a user readable text label.  Can we defined a 'labeled link' class in the ontology that is simply a {label, URI} tuple. These are implemented in schema.org JSON-LD as sdo:DefinedTerm that inherits name and identifier from sdo:Thing

**Comment by rduerr** [comment]
Since all of sdo is already in ECRRO, sdo:DefinedTerm is already in ECRRO, so I don't see what more is needed?  Are you trying to force all URI's to have a label - they all are permitted to already?

**Comment by smrgeoinfo** [comment]
Yes, looks like DefinedTerm works, but in sdo only if the range of a property includes sdo:Thing, or we define eccro property ranges for things with controlled vocabulary to include sdo:DefinedTerm (a good idea I'd say...).   
If the range is 'Text' then we have to use some syntax convention to have a labeled link  e.g. '{label, URI}' If the range is 'URI' then there is no way to attach a label that validates with sdo structured testing tool. 

So far in the implementation, we've been able to use sdo:DefinedTerm, sdo:CreativeWork, or sdo:Thing to get a name and url for linked items.  see docs at https://drive.google.com/open?id=1c6P7Yj1qqr8uBWVHkpjV7j43PVoN5bZA

**Comment by rduerr** [comment]
It seems to make sense to include `sdo:DefinedTerm` for all properties that have controlled vocabularies.  Making that so.

Is that sufficient?

**Comment by smrgeoinfo** [comment]
Should be. FYI, Here are the places that sdo:DefinedTerm is proposed for sdo implementation in the [FormsSpreadsheetsMapping2JSON-LD](https://docs.google.com/spreadsheets/d/1jUmP9aC9M5nRvw8iiiLo94D_NfIvtlFFMgYItLmlSyI/edit#gid=172544203) google sheet:


```
"ecrro:0000138": {"@type":"sdo:DefinedTerm","name":"In production", 
"identifier":"http://cor.esipfed.org/ont/earthcube/MTU/MTU_0000002"},
--
"ecrro:0000219": {"@type":"sdo:DefinedTerm","name":"More than 5 years", 
"identifier":"http://cor.esipfed.org/ont/earthcube/ELT/ELT_0000001"},

"ecrro:0000017": {"@type":"sdo:DefinedTerm", "name":"Wide usage (>50 adopters)", 
"identifier":"http://cor.esipfed.org/ont/MTU_0000002"},

"sdo:about": [{"@type":"sdo:DefinedTerm", "name":"anthropology", 
"identifier":"http://cor.esipfed.org/ont/earthcube/ADO/ADO__0000012"},
{"@type":"sdo:DefinedTerm", "name":" atmospheric chemistry", 
"identifier":"http://cor.esipfed.org/ont/earthcube/ADO/ADO__0000037"}],

"ecrro:000167": {"@type":"sdo:DefinedTerm":"name":"HTTP", 
"identifier":"http://cor.esipfed.org/ont/earthcube/CMPR_0000001"}
```

**Comment by rduerr** [comment]
Actually I think it is better to just take all of the controlled vocabularies and make them subclasses of DefinedTerm as well as dealing with the properties...

**Comment by smrgeoinfo** [comment]
Seems like that would work. In the ontology the identifier for the term is the instance identifier, and the name is the label annotation property.  I'm not sure what we'd gain by adding the subclass relation in the ontology--we'd still need an implementation rule that maps the term (instances of the vocabulary class) identifier and label to the correct sdo properties.

**Comment by rduerr** [comment]
Yes, but in the ontology you just select the instance/class you want to assign to a property and the reasoner can infer whether the assignment is correct based off the factor the instance/class is a subclass of DefinedTerm - no SHACL rule needed.

**Comment by smrgeoinfo** [comment]
so the inferencing is gained, make sense.

**Comment by rduerr** [comment]
Implemented and pushed to redwork

**Comment by rduerr** [comment]
pushed to master, anything else needed?
