### ISSUE TITLE
make redwork branch master?

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#36]
seems like the most uptodate version is the redwork branch. Can we just rename that to master?  (I can do the GitHub hacking...)

**Comment by rduerr** [comment]
I did a merge up to master at the end of last week, so no point… - Ruth

**Comment by smrgeoinfo** [comment]
master was merged into redwork, but redwork was not merged into master.

**Comment by rduerr** [comment]
Well… then it should be easy to merge into master… I will do that after adding all the DefinedTerms.

Ruth

**Comment by rduerr** [comment]
@smrgeoinfo alright, I give in.  Please make redwork master.  I can't test the widico documentation until that has happened....

**Comment by rduerr** [comment]
Done yesterday
