### ISSUE TITLE
new Term: need 'not applicable' in Usage vocabulary

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#4]
For new term requests, please provide the following information:

## Textual definition
Resource is not available for use, typically because it is still in development

## Suggested parent term
instance of 'general usage' class

## Attribution
orcid: 0000-0001-6041-5302

**Comment by rduerr** [comment]
Are we ready for this?  I wasn't quite done adding the first batch of terms when we had this faux pas earlier today.  I can see doing this when we've completed the first draft; but really until then I don't think it's a problem... Slowing things down even more than what happened today.

**Comment by rduerr** [comment]
OK, I misunderstood this issue.  I thought it was about adding a term request template, not actually adding a term.

In any case, 'not applicable' instance added to 'general usage'

**Comment by rduerr** [comment]
Released
