### ISSUE TITLE
Current version of dcat.ttl is ontologically inconsistent

### ISSUE THREAD

**Issue by rduerr** [earthcubearchitecture-ecresourcereg/ecrro#7]
While trying to debug an ontology error after adding the most recent version of dcat.ttl from the website; I ended up just loading dcat into protege and running the elk reasoner.  Strangely enough dcat itself is inconsistent with the error I was trying to debug.  The perils of using work in progress...

**Comment by smrgeoinfo** [comment]
Post an issue in the Dcat github?

https://github.com/w3c/dxwg/issues

**Comment by rduerr** [comment]
Yes but we know they aren’t done monkeying with it?  But maybe I will anyway...

**Comment by rduerr** [comment]
OBE - minimizing use of dcat in favor of schema.org for this contract but noting where harmonization will eventually be wanted.
